<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ebolito.Domain/Ebolito.Domain.csproj" />
    <ProjectReference Include="../Ebolito.Application/Ebolito.Application.csproj" />
    <ProjectReference Include="../Ebolito.Infrastructure/Ebolito.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Configuration/ebolito.configuration-contract.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
